### ISSUE TITLE
Add .iconjar file

### ISSUE THREAD

**Issue by daveyheuser** [michaelampr/jam#1]
Let me start off with that I love these icons. It would be super great if they would also come in a .iconjar file so people can easily search through the icons while designing. Alternatively an .ijmap file could work for the icon font as well (Google Material has one too https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ijmap)

More information about IconJar can be found here. Let me know if you need any help!

**Comment by michaelampr** [comment]
Hey @daveyheuser, thanks for your comment, I really appreciate. I think it's a great idea.
I'll check your links asap and come back to you.

Cheers!

**Comment by daveyheuser** [comment]
Hi Michael sorry for the delayed reply. We currently don't have an .ijmap generator but that would be pretty great! Right now the documentation on .ijmap files is pretty limited but we can definitely improve it → https://gist.github.com/daveyheuser/c6d447c27685f06b8fa5#file-ijmap-sample

I noticed you added an .IconJar file to the repo which is great. Thanks for that!
