### ISSUE TITLE
Icon Request - Quote Icon 

### ISSUE THREAD

**Issue by klcodanr** [michaelampr/jam#10]
Similar to #7 - there are a large number of great icons, but quotation is missing.

**Comment by michaelampr** [comment]
Hi @klcodanr, 
I'm working on adding a bunch of new icons and will definitely add a quote icon.
Thanks

**Comment by klcodanr** [comment]
Thanks Michael!  Two more if it would't be too much trouble :-) 

- View Source
- Unlink

**Comment by michaelampr** [comment]
Added in v3.1.0
