### ISSUE TITLE
Icon request - half star for reviews

### ISSUE THREAD

**Issue by scheMeZa** [michaelampr/jam#14]
Thank you for your hard work 👍 

I switched from font awesome, to see where I can help other libraries.

This could be considered a change request.

![image](https://user-images.githubusercontent.com/7773361/54878177-b9dad080-4e31-11e9-8bcf-5a30d55ba017.png)

I would like to display the above as 2 1/2 stars, like most ratings look:
![image](https://user-images.githubusercontent.com/7773361/54878192-e5f65180-4e31-11e9-8a43-35ed2861f163.png)

You do cater for this scenario with: star-half, but I need to use CSS to rotate by 180 degrees.

Maybe you could add another version of star-half, such as star-half-f, which is just the inverse on the x-axis? I'm not sure. I do believe the inverse would be the most common use-case for ratings.

Keep up the good work!

**Comment by michaelampr** [comment]
Hey,

Thanks for the idea and details, just added  `star-half-f` to the current todo 😉

**Comment by michaelampr** [comment]
Added in v3.1.0
