### ISSUE TITLE
jam-icons.com appears to be down

### ISSUE THREAD

**Issue by Kryten0807** [michaelampr/jam#16]
Sorry for the unorthodox way of letting you know... The "Get In Touch" link on your personal site also doesn't work...

The jam-icons.com site appears to be down. All assets (JS, CSS, etc.) are returning 404 errors.

**Comment by michaelampr** [comment]
Hey @Kryten0807 thanks for letting me know!
It has been fixed. 
I cannot reproduce the issue you encountered on my personal website but I’m curious, what was your configuration? Thanks!
