### ISSUE TITLE
Cut, copy, paste, save

### ISSUE THREAD

**Issue by lorenzos** [michaelampr/jam#3]
Thank you for the project, finally a great alternative to Google Material icons!

How about adding icons for cut, copy (`files` is ok atm), paste and save actions?

**Comment by michaelampr** [comment]
Hey @lorenzos thanks!
I like the idea. I currently have a list where I put new icons ideas, so I'll add them to it for the next version. I'll probably release a new minor version to update the current one with new icons in a few weeks. Stay tuned!

**Comment by michaelampr** [comment]
Hello @lorenzos 

I just released the v2 version with 896 icons. I re-shaped every icon to be more consistent & reliable.
 
Perhaps you don't need them anymore, but here are the icons:
cut: scissors 
copy: files, files-f
paste: clipboard, clipboard-f
save: save, save-f

**Comment by lorenzos** [comment]
Thank you!

**Comment by zadam** [comment]
> copy: files, files-f
> paste: clipboard, clipboard-f

These are good suggestions. It would be great if you could add them to search page on https://jam-icons.com/ - there's no hit on "paste" and "copy" doesn't suggest "files" (which is pretty nice but not obvious choice).

Another word I found which doesn't trigger anything was "zoom" - it might match icons with plus and minus.
