### ISSUE TITLE
file-f and 3d icons

### ISSUE THREAD

**Issue by shawnd** [michaelampr/jam#5]
Hi, love the icon set.

Could you make a variant of file, that is filled instead of outlined.

Also could you create an icon that can represent a 3D model?

**Comment by michaelampr** [comment]
Hey @shawnd thanks!
Like the suggestions! I took note to add them for the next update 👍

**Comment by michaelampr** [comment]
Hello @shawnd !

I just updated the set to v2. I added the file-f & files-f variants in this new release ;) 
Could you give me some examples for the 3D model you asked?

**Comment by michaelampr** [comment]
Hey @shawnd, since I've no info I close this issue. Do not hesitate to reopen it if you are still interested.
