### ISSUE TITLE
Optimize SVG

### ISSUE THREAD

**Issue by jenil** [michaelampr/jam#6]
I just realized the SVG's are directly the output of Sketch. I really think you should consider running them through [SVGO](https://github.com/svg/svgo) and also remove the `style` in each SVG so that the icons are more extensible.

**Comment by michaelampr** [comment]
Hey @jenil ! Thanks a lot. 
I just used SVGO with specific flags to remove extra/useless data (title, desc, style). Will update the project soon. Thanks!
